package com.powersurgepub.twodue;

  import com.powersurgepub.psdatalib.pstags.TagTreeCellRenderer;
import com.powersurgepub.psdatalib.pstags.TagsNode;
  import com.powersurgepub.twodue.data.*;
  import com.powersurgepub.twodue.disk.*;
  import javax.swing.*;
  import javax.swing.event.*;
  import javax.swing.tree.*;

/**
   A panel to display a list of items in a tree form, organized by
   Category. <p>
  
   This code is copyright (c) 2003 by Herb Bowie.
   All rights reserved. <p>
  
   Version History: <ul><li>
      2003/11/20 - Originally written.
       </ul>
  
   @author Herb Bowie (<a href="mailto:herb@powersurgepub.com">
           herb@powersurgepub.com</a>)<br>
           of PowerSurge Publishing 
           (<a href="http://www.powersurgepub.com">
           www.powersurgepub.com</a>)
  
   @version 2003/11/20 - Originally written.
 */
public class CategoryTab 
    extends javax.swing.JPanel 
        implements TwoDueTab {
          
  private TwoDueCommon   td;
  
  private TagTreeCellRenderer renderer;
  
  /** 
    Creates new form CategoryTab 
   */
  public CategoryTab (TwoDueCommon td) {
    this.td = td;
    initComponents();
  }
  
  /**
    Prepares the tab for processing of newly opened file.
   
    @param store Disk Store object for the file.
   */
  public void filePrep (TwoDueDiskStore store) {
    // No file information used on the Category (Tree) Tab
  }
  
  public void initItems() {

    catTree.setModel (td.items.getTagsModel().getModel());
    catTree.getSelectionModel().setSelectionMode
        (TreeSelectionModel.SINGLE_TREE_SELECTION);
    renderer = new TagTreeCellRenderer();
    // renderer = new TagTreeCellRenderer 
    //   (td.lateIcon, td.todayIcon, td.tomorrowIcon, td.futureIcon);
    catTree.setCellRenderer (renderer);
    catTree.doLayout();
    /*
    td.sorted.setColumnWidths (listTable);
    ItemPriorityRenderer ipr = new ItemPriorityRenderer();
    listTable.setDefaultRenderer (ItemPriority.class, ipr);
    listTable.getColumn(td.sorted.getColumnName(4)).setCellRenderer(ipr);
    td.sorted.fireTableDataChanged();
    
     */
  }
  
  public void showThisTab () {
    td.switchTabs();
  }
  
  public void displayItem() {
  }  
  
  public boolean modIfChanged() {
    return false;
  }  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    catScrollPane = new javax.swing.JScrollPane();
    catTree = new javax.swing.JTree();

    setLayout(new java.awt.BorderLayout());

    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });

    TreeSelectionModel treeSM = catTree.getSelectionModel();
    treeSM.setSelectionMode (treeSM.SINGLE_TREE_SELECTION);
    treeSM.addTreeSelectionListener (new TreeSelectionListener() {
      public void valueChanged (TreeSelectionEvent e) {
        itemSelected();
      }
    });
    catScrollPane.setViewportView(catTree);

    add(catScrollPane, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    showThisTab();
    catScrollPane.requestFocus();
  }//GEN-LAST:event_formComponentShown

  private void itemSelected() {
    TagsNode node = (TagsNode)
      catTree.getLastSelectedPathComponent();
    if (node == null) {
      // nothing selected
    } 
    else
    if (node.getNodeType() == node.ITEM) {
      // td.navigator = td.tree;
      td.selectItem ((ToDoItem)node.getUserObject());
      td.displayItem();
      if (td.selItemTab) {
        td.activateItemTab();
      }
    }
    else {
      // Do nothing until an item is selected
    }
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane catScrollPane;
  private javax.swing.JTree catTree;
  // End of variables declaration//GEN-END:variables
  
}
